### ISSUE TITLE
EPIC: Account management

### ISSUE THREAD

**Issue by mhfortuna** [rocket-team-webdev/wave#11]
- [x] user info visualization #12
- [x] user info edition #13
- [x] update password #14
- [x] Full delete account #38
