### ISSUE TITLE
EPIC: Tracks Management

### ISSUE THREAD

**Issue by mhfortuna** [rocket-team-webdev/wave#19]
Gestión de canciones

- [x] Track upload #26
- [x] See my songs #27
- [x] Like a song from list #28
- [x] Add a song to queue from list #52
- [x] Edit a song from list #30 
- [x] Delete a song from list #90
