### ISSUE TITLE
Final styling

### ISSUE THREAD

**Issue by Ricard-Garcia** [rocket-team-webdev/wave#292]
- [x] Design default images #218 
- [x] Add custom scroll bar #132 
- [x] Fix scroll bug in PC #299
- [x] Stylize radio buttons #295 
- [x] Change global colors.
